# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
      cocoapods(repo_update: true)
      danger(
             dangerfile: "Dangerfile",
             github_api_token: ENV["GITHUB_API_TOKEN"],
             verbose: true
             )
      swiftlint(
                mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
                executable: "Pods/SwiftLint/swiftlint",
                output_file: "swiftlint.result.json", # The path of the output file (optional)
                ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
                )
      scan
  end
end
